---
# defintion de la play

- hosts: servers
  name: this is a play within a playbook
  become: yes
  vars:
    httpd_packages:
      - httpd
      - mod_wsgi
    apache_test_message: this is a test message
    apache_max_keep_alive_requests: 115
#instalation des packages apache

  tasks: 
    - name: install httpd packages
      yum: 
        name: "{{ item }}"
        state: present
      with_items: "{{ httpd_packages }}"
      notify: restart apache service
#ajout de fichiers à notre playbook

    - name: create site-enabled directory
      file:
        name: /etc/httpd/conf/site-enabled
        state: directory 

    - name: copy httpd.conf
      template:
        src: /etc/ansible/playbooks/apache-simple/templates/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
      notify: restart apache service

    - name: copy index.html
      template:
        src: /etc/ansible/playbooks/apache-simple/templates/index.html.j2
        dest: /var/www/html/index.html

    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes
  
  
  handlers:
    - name: restart apache service
      service:
        name: httpd
        state: restarted
        enabled: yes
         

